export const tireFilterableFields = [
  "searchTerm",
  "name",
  "loadRange",
  "tireType",
  "category",
  "brand",
  "make",
  "model",
  "year",
  "trim",
  "tireSize",
  "price",
  "stockQuantity",
  "constructionType",
  "sectionWidth",
  "aspectRatio",
  "rimDiameter",
];

export const tireSearchableFields = [
  "name",
  "description",
  "loadRange",
  "tireType",
  "constructionType",
  "category",
  "productLine",
  "treadPattern",
];
