export const wheelFilterableFields = [
  "searchTerm",
  "name",
  "boltPattern",
  "wheelType",
  "category",
  "finish",
  "brand",
  "make",
  "model",
  "year",
  "trim",
  "tireSize",
  "drivingType",
  "price",
  "stockQuantity",
  "constructionType",
  "materialType",
  "RimDiameter",
  "RimWidth",
];

export const wheelSearchableFields = [
  "name",
  "description",
  "boltPattern",
  "wheelType",
  "constructionType",
  "category",
  "productLine",
  "finish",
  "wheelColor",
];
